// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionTimeLog
{
    internal sealed partial class Vsix
    {
        public const string Id = "SolutionTimeLog.b8e308cf-180b-43da-98af-7054b0af86dd";
        public const string Name = "Solution Time Log";
        public const string Description = @"Keeps track of the time you spend working in each solution and provides a nice overview and analysis";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "time, log";
    }
}
