// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionTimeLog
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TimeLogPackageString = "90e7ce37-4df0-4eba-a451-9094e275bcaa";
        public static Guid TimeLogPackage = new Guid(TimeLogPackageString);

        public const string TimeLogCmdSetString = "0f4b81c2-20ef-458e-8038-e1eecb90a0ee";
        public static Guid TimeLogCmdSet = new Guid(TimeLogCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int OpenTimeLog = 0x0100;
    }
}